### PR TITLE
"Downloader IP" in download history log: account for reverse-proxied requests

### PR DESCRIPTION
**Pull request by blinkingtwelve**
I've tried picoshare out today. Nice stuff!
I had stuck it behind a reverse proxy (Apache this time). But like this, in the download log (as under `/files/$THE_ID/downloads`) the "Downloader IP" of all downloads would list the IP of the proxy...

This PR will make it so that instead the client IP from the [X-Forwarded-For header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For) (which is, by convention, inserted by reverse HTTP proxies such as Apache and Nginx) is recorded.

### CODE REVIEW

**Comment by blinkingtwelve** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by blinkingtwelve** [comment]
recheck

**Comment by mtlynch** [comment]
Thanks for submitting this!

Are you seeing this behavior with `PS_BEHIND_PROXY` set to true?

https://github.com/mtlynch/picoshare#environment-variables

That should get you the correct IPs everywhere (e.g., in log files, error messages) rather than specifically in the download log.

**Comment by boerwastaken** [comment]
That indeed does the job. I hadn't read the README past all the Docker blah ;-)

Please close!

**Comment by blinkingtwelve** [comment]
That indeed does the job. I hadn't read the README past all the Docker blah ;-)

Please close!

**Pull request closed without merging**
