### PR TITLE
Add shortlink to file table

### PR DESCRIPTION
**Pull request by dertuerke**
@mtlynch i dont found a solution to add the "scheme" (http/s) to the URL. Can u give me a tip, how to get the scheme

---
This change is [Reviewable](https://reviewable.io/reviews/mtlynch/picoshare/128)

### CODE REVIEW

**Review by mtlynch — CHANGES_REQUESTED** [review]
> i dont found a solution to add the "scheme" (http/s) to the URL. Can u give me a tip, how to get the scheme

The only way I know of is to check if `r.TLS == nil`, but that won't work if we're behind a proxy that terminates the TLS connection before it reaches PicoShare. I think we should get the URL in JavaScript instead.

> *[Reviewable](https://reviewable.io/reviews/mtlynch/picoshare/128#-:-MyyVKk78G4DkH7z0H01:b-onf1jt)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @dertuerke and @mtlynch)

___
*[handlers/views.go, line 70 at r1](https://reviewable.io/reviews/mtlynch/picoshare/128#-MyyQrRv1WO00R6PVLWL:-MyyQrRv1WO00R6PVLWM:b-j4alur) ([raw file](https://github.com/mtlynch/picoshare/blob/72299ece275c4541be47f5b0d0572f62a213c9de/handlers/views.go#L70)):*
> ```Go
> 			},
> 			"formatShortlink": func(url types.EntryID) string {
> 				return r.Host + "/!" + string(url)
> ```

In this case, I think it's better to get the URL client-side through JS. If PicoShare is running behind a proxy, I don't think the server can figure out the exact URL the user originally requested.
___
*[static/js/fileIndex.js, line 30 at r1](https://reviewable.io/reviews/mtlynch/picoshare/128#-MyyU_GS9K3ZxmaX5O8K:-MyyU_GS9K3ZxmaX5O8L:bm1pe6i) ([raw file](https://github.com/mtlynch/picoshare/blob/72299ece275c4541be47f5b0d0572f62a213c9de/static/js/fileIndex.js#L30)):*
> ```JavaScript
>     input.setSelectionRange(0, 99999);
> 
>     if (navigator && navigator.clipboard && navigator.clipboard.writeText) {
> ```

This only works on HTTPS. Can we try [this method](https://stackoverflow.com/a/65996386/90388) so that it works under plaintext HTTP too?
___
*[templates/file-index.html, line 37 at r1](https://reviewable.io/reviews/mtlynch/picoshare/128#-MyyUv0ABfZtSPAMsAr1:-MyyUv0ABfZtSPAMsAr2:b58iknv) ([raw file](https://github.com/mtlynch/picoshare/blob/72299ece275c4541be47f5b0d0572f62a213c9de/templates/file-index.html#L37)):*
> ```HTML
>           <div class="field has-addons" pico-shortlink pico-entry-id="{{ .ID }}">
>             <div class="control">
>               <input class="input is-normal" type="text" value="{{ formatShortlink .ID }}" readonly>
> ```

I don't think we need to show the text. Can we do it with just the button, like this?

**Comment by dertuerke** [comment]
@mtlynch i remove the old fn from go and write is back in JS and I add a snackbar to notify the user.

**Review by mtlynch — CHANGES_REQUESTED** [review]
This is cool. This works for me now in a dev environment.

I like the snackbar behavior. Very simple and nice UX!

I have a few small notes but it's almost ready to merge in.

> *[Reviewable](https://reviewable.io/reviews/mtlynch/picoshare/128#-:-Mz00JaH3hrqUcE9Vz18:b-bjmsra)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @dertuerke and @mtlynch)

___
*[static/js/fileIndex.js, line 34 at r2](https://reviewable.io/reviews/mtlynch/picoshare/128#-Mz0-SHoAqcUJadvHPI7:-Mz0-SHoAqcUJadvHPI8:bcty2b2) ([raw file](https://github.com/mtlynch/picoshare/blob/b770044721b71810c72967e64d333a31db8a9035/static/js/fileIndex.js#L34)):*
> ```JavaScript
>   copyBtn.addEventListener("click", () => {
>     const picoId = copyBtn.getAttribute("pico-entry-id");
>     const shortLink = `${window.location.origin}/!${picoId}`;
> ```

I'd rather not duplicate logic for generating shortlinks, so I just created a helper method. Can we use this?

https://github.com/mtlynch/picoshare/blob/43d3b2bb6c8b1a4abcc198f7813a3eb14b3eda78/static/js/lib/links.js#L1
___
*[static/js/fileIndex.js, line 52 at r2](https://reviewable.io/reviews/mtlynch/picoshare/128#-Mz-zqHC8aYBCv-FJuk6:-Mz-zqHC8aYBCv-FJuk7:b-r1au17) ([raw file](https://github.com/mtlynch/picoshare/blob/b770044721b71810c72967e64d333a31db8a9035/static/js/fileIndex.js#L52)):*
> ```JavaScript
>   // navigator clipboard api needs a secure context (https)
>   if (navigator.clipboard && window.isSecureContext) {
>     // navigator clipboard api method'
> ```

We can delete this comment
___
*[static/js/fileIndex.js, line 55 at r2](https://reviewable.io/reviews/mtlynch/picoshare/128#-Mz-zrVq72fuhAWAjTQ9:-Mz-zrVq72fuhAWAjTQA:b-r1au17) ([raw file](https://github.com/mtlynch/picoshare/blob/b770044721b71810c72967e64d333a31db8a9035/static/js/fileIndex.js#L55)):*
> ```JavaScript
>     return navigator.clipboard.writeText(textToCopy);
>   } else {
>     // text area method
> ```

We can delete this comment
___
*[static/js/fileIndex.js, line 58 at r2](https://reviewable.io/reviews/mtlynch/picoshare/128#-Mz-zu_dAz8DUpxmQsWM:-Mz-zu_dAz8DUpxmQsWN:bn1raw0) ([raw file](https://github.com/mtlynch/picoshare/blob/b770044721b71810c72967e64d333a31db8a9035/static/js/fileIndex.js#L58)):*
Can we format this so it matches the style of other comments in our code?

> Make the textarea out of viewport.
___
*[static/js/fileIndex.js, line 66 at r2](https://reviewable.io/reviews/mtlynch/picoshare/128#-Mz-zt8t3mhfrgRbmHx0:-Mz-zt8t3mhfrgRbmHx1:b-r1au17) ([raw file](https://github.com/mtlynch/picoshare/blob/b770044721b71810c72967e64d333a31db8a9035/static/js/fileIndex.js#L66)):*
> ```JavaScript
>     textArea.select();
>     return new Promise((res, rej) => {
>       // here the magic happens
> ```

We can delete this comment
___
*[static/js/fileIndex.js, line 78 at r2](https://reviewable.io/reviews/mtlynch/picoshare/128#-Mz0-dba5tsC_1sH01Cf:-Mz0-dba5tsC_1sH01Cg:bv9kewo) ([raw file](https://github.com/mtlynch/picoshare/blob/b770044721b71810c72967e64d333a31db8a9035/static/js/fileIndex.js#L78)):*
> ```JavaScript
> 
>   el.classList.add("snackbar");
>   el.innerHTML = "Link was copied!";
> ```

Can we make the snackbar text a parameter so that calls look like `createSnackbar("Link was copied!")`

**Comment by dertuerke** [comment]
@mtlynch i refractor the snackbar and put it out in separate files and the clipboard func, too.
So okay?

**Review by mtlynch — APPROVED** [review]
:lgtm: 

Thanks!

> *[Reviewable](https://reviewable.io/reviews/mtlynch/picoshare/128#-:-Mz2NLgxD4zO8kvG4ahC:b-41s8zb)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @dertuerke and @mtlynch)

**Pull request merged**
