### PR TITLE
Replace Google Web Fonts with local integration

### PR DESCRIPTION
**Pull request by dertuerke**
Hi, I have replaced the external integration of Google Fonts. I downloaded the fonts and integrated them as an internal resource. The Google web fonts are tracked.

I hope I did everything right in the Go file :D
It's my first time to work with Go.

### CODE REVIEW

**Comment by dertuerke** [comment]
@mtlynch what i make wrong her :S

**Comment by dertuerke** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mtlynch** [comment]
Thanks! Can we adjust the paths so that they're like this?

* `static/third-party/google-fonts/css/fonts.css`
* `static/third-party/google-fonts/fonts/karla-v21-latin/karla-v21-latin-200.woff`

**Comment by mtlynch** [comment]
Looks good, thanks!

**Pull request merged**
